### ISSUE TITLE
isSubmitted and isValid not working

### ISSUE THREAD

**Issue by psren** [LinioIT/dynamic-form-bundle#10]
My form renders correctly and is a very simple configuration.
If i submit is neighter ```isSubmitted()``` nor ```isValid()``` do work.

```yaml
dynamic_form:
    new_user:
        title:
            enabled: true
            type: text
        password:
            enabled: true
            type: password
        meta_keywords:
            enabled: true
            type: textarea
        meta_description:
            enabled: true
            type: textarea
        published:
            enabled: true
            type: checkbox
```

```php
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        // Create the dynamic form
        /** @var \Symfony\Component\Form\Form $form */
        $form = $this->get('dynamic_form.factory')->createForm('new_user');

        $form->isSubmitted(); // never works. Not after submission.

        // replace this example code with whatever you need
        return $this->render('default/index.html.twig', array(
            'form' => $form->createView(),
        ));
    }
```

```html
<form action="/" method="POST">
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-primary">Speichern</button>
</form>
```
