### ISSUE TITLE
Choices field doesn't work

### ISSUE THREAD

**Issue by psren** [LinioIT/dynamic-form-bundle#12]
I have problems getting the choices-field to work.
It doesn't seem to work at all.

Do you have an example on how to configure it properly?

```yaml
choice1:
    type: choice
        options:
              choices:
                   - One
                   - Two
```

**Comment by xurumelous** [comment]
Your Yaml is not correctly formatted.

```yaml
choice1:
    type: choice
    options:
          choices:
               - One
               - Two
```

The `options` field must be inside `choice1`, not `type`.

**Comment by psren** [comment]
In fact this was a formatting issue when posting to github.
This is my complete file and it doesn't work.

```yaml
dynamic_form:
    new_user:
        choice1:
            type: choice
            options:
                choices:
                    - One
                    - Two
```
